"""add created_at timestamps

Revision ID: 1c4a9a236d1b
Revises: 23308872356e
Create Date: 2026-07-20 23:21:16.746102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4a9a236d1b'
down_revision: Union[str, Sequence[str], None] = '23308872356e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urldb', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),  nullable=False))
    op.add_column('userdb', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdb', 'created_at')
    op.drop_column('urldb', 'created_at')
    # ### end Alembic commands ###
