"""add link_username

Revision ID: 2a69d55e5073
Revises: 1c4a9a236d1b
Create Date: 2026-07-22 09:37:03.566174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '2a69d55e5073'
down_revision: Union[str, Sequence[str], None] = '1c4a9a236d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urldb', sa.Column('link_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('urldb', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_urldb_shorturl'), table_name='urldb')
    op.create_index(op.f('ix_urldb_link_username'), 'urldb', ['link_username'], unique=True)
    op.alter_column('userdb', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userdb', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_urldb_link_username'), table_name='urldb')
    op.create_index(op.f('ix_urldb_shorturl'), 'urldb', ['shorturl'], unique=False)
    op.alter_column('urldb', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('urldb', 'link_username')
    # ### end Alembic commands ###
